### ISSUE TITLE
Implement Uninstall

### ISSUE THREAD

**Issue by vdice** [deislabs/porter-azure#7]
Implement uninstall functionality via [uninstall.go](https://github.com/deislabs/porter-azure/blob/master/pkg/azure/uninstall.go)

**Comment by jeremyrickard** [comment]
I think this has been fixed already by https://github.com/deislabs/porter-azure/commit/237b4f536ce6efe90a2157ce45355d50da20d1d7.

**Comment by vdice** [comment]
@jeremyrickard I'm not seeing an uninstall implementation in that linked commit... https://github.com/deislabs/porter-azure/blob/master/pkg/azure/uninstall.go still shows just `return nil`.

**Comment by jeremyrickard** [comment]
I commented on the wrrrrrrrrronnnnnnng issue :)

**Comment by jeremyrickard** [comment]
I am working on a PR for this though! I had both issues open, hence my bad commenting :)
